// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parcial_113917_Coniglio_Gabriel.Models;

#nullable disable

namespace Parcial_113917_Coniglio_Gabriel.Migrations
{
    [DbContext(typeof(Prog3AerolineasContext))]
    partial class Prog3AerolineasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Avione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadAsientos")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadMotores")
                        .HasColumnType("integer");

                    b.Property<string>("DatosVarios")
                        .HasColumnType("text");

                    b.Property<int>("IdFabricante")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Aviones_pk");

                    b.HasIndex(new[] { "IdFabricante" }, "fki_fabricante");

                    b.ToTable("Aviones");
                });

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Fabricantes_pk");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Usuarios_pk");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Avione", b =>
                {
                    b.HasOne("Parcial_113917_Coniglio_Gabriel.Models.Fabricante", "IdFabricanteNavigation")
                        .WithMany("Aviones")
                        .HasForeignKey("IdFabricante")
                        .IsRequired()
                        .HasConstraintName("fabricante");

                    b.Navigation("IdFabricanteNavigation");
                });

            modelBuilder.Entity("Parcial_113917_Coniglio_Gabriel.Models.Fabricante", b =>
                {
                    b.Navigation("Aviones");
                });
#pragma warning restore 612, 618
        }
    }
}
